version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000 # nodejs
      - 1234:1234 # python
    environment:
      - CHOKIDAR_USEPOLLING=true